### PR TITLE
Chantal

### PR DESCRIPTION
**Pull request by mhsdesign**

### CODE REVIEW

**Comment by dfeyer** [comment]
It-s a take over PR ... not sure I will merge it here, no ?

I'm working on version compatible with Neos 7/8 actually

**Comment by mhsdesign** [comment]
Hmm haha sorry yes... so i actually dont remember what we wanted to do at the frankfurt sprint. I remember $someone asked me to fork this package to FlowPack so we can maintain this but i found this package a bit to big and possibly not ready enough to be a FlowPack.

> Package under development, API can change at any time

Thats why i suggested to fork it to `Carbon.OutOfBandRendering` and release it together with @jonnitto and take care that it works with never neos versions.

But i think i understand what happened, since this was forked to `Carbon.OutOfBandRendering` this rename PR was made accidentally against your original repo and thus got lost. That being said. `Carbon.OutOfBandRendering` is a non working fork and not on packagist and probably not even really working ^^

> I'm working on version compatible with Neos 7/8 actually

Actually that would be of course brilliant, we just thought that you werent active anymore ^^

... Oh now i remember why we did this ... @kdambekalns made a fork https://github.com/kdambekalns/OutOfBandRendering which is used for a Neos website like the docs maybe? and we wanted to get rid of this github dependency and get it on packagist ;)

**Comment by dfeyer** [comment]
> Actually that would be of course brilliant, we just thought that you werent active anymore ^^

I'm back to some activity

**Comment by dfeyer** [comment]
I will release a Neos 7.3 + 9 version this week

**Comment by dfeyer** [comment]
https://packagist.org/packages/ttree/outofbandrendering

3.1.0 is out

**Comment by mhsdesign** [comment]
Thank you so much :D Feel free to write that in slack so we can ditch our forks ^^

**Comment by kdambekalns** [comment]
> @kdambekalns made a fork https://github.com/kdambekalns/OutOfBandRendering which is used for a Neos website like the docs maybe?

Indeed, for neos.io, see https://github.com/neos/Neos.NeosIo/blob/17a706172f41844ee4bb66c62dc2cf2615fefa67/composer.json#L54

~We could have long removed the fork, though, see https://github.com/ttreeagency/OutOfBandRendering/pull/3 🤷~

Obviously I never created a PR…

**Pull request closed without merging**
