### PR TITLE
 !!! TASK: Use Neos FusionView, rename TypoScript to Fusion, update code style

### PR DESCRIPTION
**Pull request by kdambekalns**
Marked as breaking, since the `PresetDefinitionInterface` has changed.
You need to add type declarations and change the name of the method
`getTypoScriptPath` to `getFusionPath`.

### CODE REVIEW

**Comment by kdambekalns** [comment]
This must become a new major version, @dfeyer has to judge if a branch is needed for older versions to be updated in the future.

The 2.0.1 could be replaced by a 2.0.2 that no longer claims to be compatible with Neos 4.x, as that isn't true…

**Comment by kdambekalns** [comment]
Hi @dfeyer – could you take a look here? Thanks!

**Comment by dfeyer** [comment]
Thanks I merge it a release a new major right now

**Comment by dfeyer** [comment]
2.0.2 released with fixed Neos dependencies

**Pull request merged**
